[package]
name = "bd_rtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oracle = "0.6.2"
ping-rs = "0.1.2"
telnet = "0.2.1"

[profile.release]
opt-level = 3
